; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool on Tue May 01 2018 15:46:33 GMT+0300 (FLE Summer Time)
G91               ; relative positioning
G1 S1 X-150 F1800 ; move quickly to X axis endstop and stop there (first pass)
G1 X5 F6000       ; go back a few mm
G1 S1 X-150 F360  ; move slowly to X axis endstop once more (second pass)
G90               ; absolute positioning